version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: quiz-educacional-api
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    command: npm run dev-docker
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    # volumes:
    #   - /home/renatogroffe/Desenvolvimento/Docker-Compose/PostgreSQL:/var/lib/postgresql/data 
  # pgadmin4:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
  #     PGADMIN_DEFAULT_PASSWORD: "admin"
  #   ports:
  #     - "3001:80"
  #   depends_on:
  #     - db
